apiVersion: v1
kind: ConfigMap
metadata:
  name: html-content
  namespace: my-app
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Cloud Platform</title></head>
    <body style="background-color: #2c3e50; color: white; text-align: center; padding-top: 100px; font-family: sans-serif;">
      <h1>🚀 Plataforma Felipe Carpanezi funcionando!</h1>
      <p>Deploy via GitOps + ArgoCD + AWS EKS</p>
      <div style="color: #27ae60;">● Online</div>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: html-content
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: my-app
spec:
  selector:
    app: web
  ports:
  - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: my-app
spec:
  ingressClassName: nginx
  rules:
  - host: meu-site.52.202.46.203.sslip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-service
            port:
              number: 80