apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
spec:
  project: default
  source:
    chart: rancher
    repoURL: https://releases.rancher.com/server-charts/stable
    targetRevision: 2.8.2
    helm:
      values: |
        hostname: rancher.3.223.58.250.sslip.io
        bootstrapPassword: admin
        replicas: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true