apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
spec:
  project: default
  source:
    chart: rancher
    repoURL: https://releases.rancher.com/server-charts/stable
    targetRevision: 2.9.2 # Versão estável para K8s 1.29
    helm:
      # Esse comando força o Helm a ignorar a versão real do EKS na validação
      kubeVersion: 1.28.0 
      values: |
        hostname: rancher.3.223.58.250.sslip.io
        bootstrapPassword: admin
        replicas: 1
        ingress:
          ingressClassName: nginx
        tls:
          source: rancher
  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true